version: '3.8'

services:
  gavottesai:
    build: .
    container_name: gavottesai_container
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    env_file:
      - .env
    restart: always
